# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
# SPDX-License-Identifier: MIT

name: Fuzzing

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fuzz:
    name: Fuzz Testing
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    strategy:
      fail-fast: false
      matrix:
        target:
          - fuzz_new_from_strings
          - fuzz_from_cstrings
          - fuzz_pointer_operations
          - fuzz_try_from

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          key: fuzz-${{ matrix.target }}

      - name: Install cargo-fuzz
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-fuzz

      - name: Run fuzzer
        run: cargo fuzz run ${{ matrix.target }} -- -max_total_time=300
        env:
          RUST_BACKTRACE: 1

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fuzz-artifacts-${{ matrix.target }}
          path: fuzz/artifacts/${{ matrix.target }}
